[package]
name = "registration_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
rocket_contrib = "0.5.0-rc.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "1.4", features = ["sqlite"] }
dotenv = "0.15"
